### ISSUE TITLE
Fix on saving creating broken code

### ISSUE THREAD

**Issue by sgwilym** [apexskier/nova-eslint#10]
Since last week, the fix-on-save feature has started leaving me with broken code:

Before:
<img width="452" alt="FC704D10-E547-412D-B873-B65855011F50" src="https://user-images.githubusercontent.com/579491/97978335-b9f0cf80-1dcd-11eb-8add-b63ef7f606a5.png">

After:
<img width="363" alt="EB9882CC-6A2A-4E02-A09B-9915AF188833" src="https://user-images.githubusercontent.com/579491/97978340-bbba9300-1dcd-11eb-9c84-fb593e41297d.png">

**To reproduce**

I find it very hard to consistently reproduce this bug. It seems to happen around half the time I save. I have no competing extensions working on the same files. I'm also really unsure if this has anything to do with the loaded eslint config.

**Environment**

- Nova version: 213794
- Extension version: 1.5.0
- ESLint version: v7.11.0
- macOS version: 10.15.7 (19H2)
- NodeJS information:
  - node version: v14.4.0
  - npm version: 6.14.4
  - installation method: homebrew

**Additional context**

Could this have anything to do with this change?

> When fixing all issues, apply fixes atomically in editor before saving (way faster)

**Comment by apexskier** [comment]
Yes, this is caused by the latest release. I was afraid of this happening. 

The new functionality applies all the fixes suggested but eslint directly in the editor, but because they are represented as text positions and they mutate the document and change the text structure they can conflict. I attempted to avoid this by applying them in reverse order, but apparently that doesn't work. I'll have to look at how eslint itself actually resolved cascading fixes or manually track how the fix ranges are affecting other fix ranges.

**Comment by apexskier** [comment]
Working on this in https://github.com/apexskier/nova-eslint/pull/11 if you want to try it out locally.

**Comment by sgwilym** [comment]
As always, thank you for your stewardship @apexskier!
