### ISSUE TITLE
ESLint auto-fix on save takes ~5 seconds. Is this expected behavior?

### ISSUE THREAD

**Issue by benlevy0** [apexskier/nova-eslint#101]
I'm on the free trial and am used to eslint auto-fixing roughly instantly (certainly taking less than 1 second) on Atom and VSCode. Nova is native so I suspect the issue is with the extension, not the app. Is this expected behavior or is there something wrong with my setup?

[The Prettier extension](https://github.com/alexanderweiss/nova-prettier) works instantly, with no lag.

**Comment by benlevy0** [comment]
For reference, here is my .eslintrc.js:

```javascript
module.exports = {
	env: {
		es2020: true,
		node: true,
		jest: true
	},
	extends: ['@react-native-community', 'airbnb', 'prettier', 'prettier/react'],
	parserOptions: {
		ecmaFeatures: { jsx: true },
		ecmaVersion: 11,
		sourceType: 'module'
	},
	plugins: ['react', 'simple-import-sort'],
	rules: {
		curly: ['error', 'multi-line'],
		'import/order': 'off',
		'simple-import-sort/imports': 'error',
		'max-len': ['error', { code: 120, ignoreUrls: true }],
		'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
		'react/prop-types': [2, { skipUndeclared: true }],
		'react-hooks/exhaustive-deps': ['error', { additionalHooks: 'useRecoilCallback' }]
	}
};
```

**Comment by apexskier** [comment]
This is expected with how this extension currently works.

The main mechanism this uses is running the eslint cli in an external process for each lint/fix run, which takes the time you're seeing. (This mechanism predates my [fork](https://github.com/apexskier/nova-eslint#fork))

I've implemented "client side" fixing that's much faster (by manually fixing the extension-tracked issues), but it has some edge cases I haven't taken the time to work through that mean I always run the external fixer as well.

I suspect the reason that client side fixing doesn't appear work in fix on save is because the editor changes and the extension marks it dirty before the `onWillSave` callback is handled, so there are no tracked issues at that point.

The prettier extension implements a JSON RPC server that it runs in an external process (["prettier service"](https://github.com/alexanderweiss/nova-prettier/blob/df11b02889e45f438270b5ecbece26d9fe03fbc8/src/Scripts/main.js#L135)) that manages formatting. I could probably do something like this here using the [eslint node api](https://eslint.org/docs/developer-guide/nodejs-api). I'd expect to be faster since it probably would have better cacheing behavior and wouldn't require the overhead of restarting a node program for each file. There'd be more complexity and I'd have to think through a few compatibility issues though.

**Comment by muuvmuuv** [comment]
The VS Code ESLint extension does quit the same as the Nova Prettier extension, seems like the only way to get to that performance. For additional performance, maybe allow running the ESLint Server with a different JS Server Engine like Deno or Bun?

https://github.com/microsoft/vscode-eslint/blob/main/server/src/eslintServer.ts

**Comment by FilipAben** [comment]
Problem with using the eslint api might be that the extension doesn't run in node, but in JavascriptCore. VSCode doesn't have that problem. Might be some incompatibilities there. 
Alternatively, could also look at supporting eslint_d, which runs a daemon process to do the linting.

**Comment by patrickfatrick** [comment]
Just chiming in, I have not found any issues with using eslint_d, which does significantly speed up linting.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
