### ISSUE TITLE
Unable to run Eslint on monorepos

### ISSUE THREAD

**Issue by davidbonnet** [apexskier/nova-eslint#17]
The `nova-eslint` plugin cannot run Eslint when it resides in a project that does not install it at the very root of it.
Projects might consists of more than just one Node.js environment (e.g., a Go server and a TypeScript frontend), that would each reside in their subfolders.

**To reproduce**

1. Setup a project with folders ./a and ./b
2. Install `eslint` along with a plugin (e.g. "eslint-plugin-import") in ./a (thus the `eslint` executable is in `./a/node_modules/.bin/eslint`)
3. Configure `eslint` in `./a/package.json`
4. Set "Path to ESLint executable" preference of `nova-eslint` to `./a/node_modules/.bin/eslint`
5. See error in the plugin console:

```
ESLint[21:50:33.470000] 
Oops! Something went wrong! :(

ESLint: 6.6.0.

ESLint couldn't find the plugin "eslint-plugin-import".

(The package "eslint-plugin-import" was not found when loaded as a Node module from the directory "/path/to/project".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-import@latest --save-dev

The plugin "eslint-plugin-import" was referenced from the config file in "--config".

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.

```

**Expected behavior**

The plugin should be able to run Eslint and resolve paths based on the file it lints. Eslint might not have to be installed at the very root of the project.

**Environment**

- Nova version: 3
- Extension version: 1.5.1
- ESLint version: 6.6.0
- NodeJS information:
  - node version: 12

**Comment by apexskier** [comment]
Before I look into this more, have you configured the "Path to ESLint executable" preference to specify the location of your installation? ([see the setup instructions](https://github.com/apexskier/nova-eslint#setup))

**Comment by davidbonnet** [comment]
Indeed. Forgot to add step 4.

**Comment by apexskier** [comment]
This is happening because the extension runs eslint from the [root of your Nova workspace](https://github.com/apexskier/nova-eslint/blob/6a2955df3dff623640101b612e883dbaec0203ca/src/process.ts#L60), and for your setup `node_modules` dependencies aren't installed there. If I fix this so it runs in the correct place I think this will be resolved.

I have a couple possible approaches to fix this:

1. Try to infer the location of your node modules based on the custom eslint executable location (if it's .../node_modules/.bin/eslint do .../). This feels fragile to me, given that someone might point towards ./node_modules/eslint/bin/eslint.js or something.
2. Add a "project root" (with better naming) preference that allows you to specify the base directory (where the package.json is) of your monorepo's eslint applicable stuff. Then the extension can automatically find the correct working dir and eslint executable based on that
3. Add a "working dir" preference that allows you just manually specify where to run eslint from. This is a bit simpler and more powerful than option 2, but might be harder for some people. 

I'm leaning towards 3, but with the auto-executable resolution from 2 added as well.

**Comment by aquillano** [comment]
I believe how most extensions handle this is by traversing up the file hierarchy to 1) find the eslintrc.json (or other valid name) and 2) find the node_modules folder containing eslint, closest to the source file.

**Comment by apexskier** [comment]
I'm actually not reproducing this as I expected to. Things are working fine in the minimal reproduction I tried to set up following the reproduction notes. I did no configuration errors at first, but the configuration path option resolves that.

See https://github.com/apexskier/nova-eslint-17-reproduction

<img width="716" alt="test – test js - Nova - 2021-01-24 at 18 34 54" src="https://user-images.githubusercontent.com/329222/105638434-dc493500-5e72-11eb-93c5-e61e04448af4.png">

I also played around on the cli trying running eslint from outside of a project and wasn't seeing the reported error there.

**Comment by apexskier** [comment]
I'm using eslint 7, which might be the difference

**Comment by apexskier** [comment]
Yep, I reproduce using eslint 6. Given that eslint 7 does _not_ reproduce this issue, my advice is to upgrade.

If you have an urgent need for this, please open a PR.

Adding a working dir preference would be preferred. That'll allow people on old versions of eslint to modify behavior without adding the overhead of auto-detection for eslint 7+.

**Comment by davidbonnet** [comment]
I'm using https://github.com/kopischke/microESLint.nova now and it works with Eslint 6.

**Comment by apexskier** [comment]
⚠️ **Archived**: Although it was fun to build my nova extensions, I haven't ended up using Nova regularly and can't devote the time to maintenance. Feel free to reach out if you want to fork and start maintaining an alternative.
