### ISSUE TITLE
Crash on saving on nova 8

### ISSUE THREAD

**Issue by gnattu** [apexskier/nova-eslint#231]
After updating to nova8, this plugin crashes nova on save, and nova works fine after I disabled this plugin.

FixOnSave option is disabled 

After removing below block the plugin functions normally. Is Nova breaking or we have to change how this works?

https://github.com/apexskier/nova-eslint/blob/main/src/main.ts#L69-L76

**Comment by gmapnl** [comment]
same problem

**Comment by gnattu** [comment]
I recieved official response from Nova Support: 

> We've gotten a few reports of crashes when saving in Nova 8, and it appears to be related to new functionality in Nova 8 around extensions that can act on your files when saving (LSPs, formatters, linters, etc.). We think we've identified the problem and are working to get a fix out as soon as possible. In the meantime, disabling any extensions with language servers or with save-related functionality should work around this crash. Please let us know if you're still seeing this crash even without any extensions enabled, however. Alternatively, you can download Nova 7.5 from here and use it until we can release an update to fix this.

> We appreciate while your patience while we work to get this fixed, and thanks for reaching out!

The Nova 7.5 link is [here](https://download.panic.com/nova/Nova%207.5.zip)

**Comment by oddjones** [comment]
Yep - same here - on quite a few extensions to be fair - Ah, Panic.

**Comment by safetypins** [comment]
I've narrowed a crash editing `*.js` files down to this extension. Nova 8 crashes when trying to save `*.js` files, and doesn't crash on Save when this extension is disabled.

**Comment by apexskier** [comment]
@gnattu Thanks for reaching out to Panic.

Any hard crash of Nova isn't something I'm really able to directly fix in the extension without it feeling hacky, since full crashes make it much harder to identify the source issue (dev tools also crash). If the editor extension environment is robust enough, it should always be able to handle extension behavior without a full editor crash.

[I've confirmed that Nova 8 has no breaking changes documented, so I think we'll need to wait for a patch from Panic](https://nova.app/releases/#v8).

**Comment by apexskier** [comment]
Nova 8.1 is out with a probable fix

> Resolved a crash when two or more extensions are installed that interact with document saves

**Comment by gnattu** [comment]
The crash is gone for me after updating to Nova 8.1

**Comment by apexskier** [comment]
Hearing reports in another extension that the crash is fixed as well.
